### ISSUE TITLE
Link to Github to prevent 'too many requests' on nbviewer

### ISSUE THREAD

**Issue by Tom-van-Woudenberg** [mbakker7/exploratory_computing_with_python#14]
As the nbviewer links may result in the error message 'too many requests', could you refer the notebooks to the corresponding GitHub-page itself?

**Comment by mbakker7** [comment]
thanks for the report. @muldernielsdeltares figured out how to solve this.
fixed with https://github.com/mbakker7/exploratory_computing_with_python/pull/15
